name: Build SMS Yard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⬇⬇⬇ الخطوة الجديدة المهمّة
      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 8.9

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build debug APK
        run: ./gradlew assembleDebug    # ← wrapper اتولّد دلوقتي

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SMSYard-debug
          path: app/build/outputs/apk/debug/app-debug.apk
